  - name: "Baixa o pacote do Worpress 5.4.1"
    get_url:
      url: https://wordpress.org/wordpress-5.4.1.zip
      dest: /tmp/wordpress-5.4.1.zip
  - name: "Descompacta o wordpress"
    unarchive:
      src: /tmp/wordpress-5.4.1.zip
      dest: /var/www
      remote_src: yes
    become: yes
  - name: Copia a config de exemplo
    copy:
      src: "{{ wp_install_dir }}/wp-config-sample.php"
      dest: "{{ wp_install_dir }}/wp-config.php"
      remote_src: yes
    become: yes
  - name: Configura o wordpress
    replace:
      path: "{{ wp_install_dir }}/wp-config.php"
      regexp: "{{ item.regex }}"
      replace: "{{ item.value }}"
    with_items:
      - { regex: 'localhost', value: '{{ wp_db_ip }}' }
      - { regex: 'database_name_here', value: '{{ wp_db_name }}' }
      - { regex: 'username_here', value: '{{ wp_db_user }}' }
      - { regex: 'password_here', value: '{{ wp_db_pwd }}' }
    become: yes
  - name: Copia a config do Apache
    template:
      src: templates/000-default.conf.j2
      dest: /etc/apache2/sites-available/000-default.conf
    become: yes
    notify: Reinicia Apache